services:
  postgres:
    image: postgres:16-alpine
    container_name: subilgi-postgres
    restart: always
    command: -p 5435
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5435:5435"
    volumes:
      - subilgi_pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5435 -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/atalayyoluc/subilgisurvey/api:latest
    container_name: subilgi-api
    restart: always
    ports:
      - "5083:5083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ApplyMigrationsOnStartup=true
      # Şifre ve DB bilgilerini .env'den çekiyoruz
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5435;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD};Pooling=true;Minimum Pool Size=0;Maximum Pool Size=50;Connection Idle Lifetime=300;
    depends_on:
      postgres:
        condition: service_healthy

  ui:
    image: ghcr.io/atalayyoluc/subilgisurvey/ui:latest
    container_name: subilgi-ui
    restart: always
    ports:
      - "3333:3000"
    depends_on:
      - api

volumes:
  subilgi_pgdata_prod: